name: Build Graphics-Samples
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Generate Shader Sources
      run: Script/generate_shaders.py
    - name: Get Cache Directory
      id: cache-dir
      run: |
           echo ::set-output name=dir::%CD%
      shell: cmd
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/Dependencies
        key: Windows-dep-ver-0
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
      shell: cmd
    - name: Build Release
      run: make release
      shell: cmd
    - name: Build Debug
      run: make debug
      shell: cmd
